### ISSUE TITLE
Is it possible to do that on db side?

### ISSUE THREAD

**Issue by zhurlik** [Brest-Java-Course-2018/Dmitriy-Shestak#2]
I think that this logic can be done in the db via adding 'unique' to a column

https://github.com/Brest-Java-Course-2018/Dmitriy-Shestak/blob/005604591e00d456e657c157766b820d572b6220/dao/src/main/java/com/moro/dao/implementation/BeerDaoImpl.java#L116-L126

**Comment by Moro69** [comment]
thanks for the help

**Comment by zhurlik** [comment]
that's more better, I hope that you felt how unit tests worked and helped you to do changes and refactoring,
because they caught your updates
