### ISSUE TITLE
Why did you include verbs into urls: delete, edit etc

### ISSUE THREAD

**Issue by zhurlik** [Brest-Java-Course-2018/Dmitriy-Shestak#3]
HTTP Request Methods have enough information about action that you would like to execute

https://github.com/Brest-Java-Course-2018/Dmitriy-Shestak/blob/7b63174a220932ebe0110c2c49660d5556e30100/web-app/src/main/java/com/moro/web_app/controllers/BeerWebController.java#L129

**Comment by Moro69** [comment]
to better understanding of what actions are performed on the object. Is that a bad practice?

**Comment by zhurlik** [comment]
For better understanding there are a lot of other things such as javadoc, swagger etc.
Look at this https://restfulapi.net/resource-naming/ and read 
Never use CRUD function names in URIs

**Comment by Moro69** [comment]
Thanks for the article, I fixed my rest URIs, but what about urls for web pages? Can it contain CRUD function names, so that user can see on which page he is?

**Comment by zhurlik** [comment]
That's an another story that depends on your needs:
- how do you want it should be presented to final user 
- is it internal or public web app
- how it will be indexed by search engines
- is it SPAs or PWAs etc.
